version: '3.4'

services:
  catalogdb:
    image: mongo
    ports:
      - "27017:27017"
  
  basketdb:
    image: redis:alpine
    ports:
      - "6379:6379"
    
  discountdb:
    image: postgres
  
  pg_admin:
    image: dpage/pgadmin4
    
        
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    ports:
      - "9000:8080"
  
  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
    ports:
      - "9001:8081"
  
  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: Services/Discount/Discount.API/Dockerfile
  

volumes:
  mongo_data:
  portainer_data:
  postgres_data:
  pgadmin_data: